import type { Intent } from '../intent/schema.js';

/** Generate _index.md content listing all active intents */
export function buildIndex(intents: Intent[]): string {
  const active = intents.filter((i) => i.frontmatter.status === 'active');
  const proposed = intents.filter((i) => i.frontmatter.status === 'proposed');
  const deprecated = intents.filter(
    (i) => i.frontmatter.status === 'deprecated',
  );

  const lines: string[] = [
    '# Intent Index',
    '',
    `_Generated by \`anhcompass compile\` — do not edit manually._`,
    '',
  ];

  if (active.length > 0) {
    lines.push('## Active', '');
    for (const i of active) {
      lines.push(
        `- **[${i.frontmatter.id}](${i.frontmatter.id}.md)** — ${i.frontmatter.title}`,
      );
    }
    lines.push('');
  }

  if (proposed.length > 0) {
    lines.push('## Proposed', '');
    for (const i of proposed) {
      lines.push(
        `- [${i.frontmatter.id}](${i.frontmatter.id}.md) — ${i.frontmatter.title}`,
      );
    }
    lines.push('');
  }

  if (deprecated.length > 0) {
    lines.push('## Deprecated', '');
    for (const i of deprecated) {
      lines.push(
        `- ~~[${i.frontmatter.id}](${i.frontmatter.id}.md)~~ — ${i.frontmatter.title}`,
      );
    }
    lines.push('');
  }

  lines.push(`_Total: ${intents.length} intent(s)_`);
  return lines.join('\n');
}
